"""initial schema

Revision ID: be9ed54a2e07
Revises: 
Create Date: 2026-02-08 12:58:44.501340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be9ed54a2e07'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=100), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('parent_sku', sa.String(length=100), nullable=True),
    sa.Column('variant_sku', sa.String(length=100), nullable=True),
    sa.Column('product_type', sa.String(length=50), nullable=True),
    sa.Column('brand_code', sa.String(length=50), nullable=True),
    sa.Column('brand_name', sa.String(length=100), nullable=True),
    sa.Column('vendor_code', sa.String(length=50), nullable=True),
    sa.Column('vendor_name', sa.String(length=100), nullable=True),
    sa.Column('category_code', sa.String(length=50), nullable=True),
    sa.Column('category_1', sa.String(length=100), nullable=True),
    sa.Column('category_2', sa.String(length=100), nullable=True),
    sa.Column('category_3', sa.String(length=100), nullable=True),
    sa.Column('category_4', sa.String(length=100), nullable=True),
    sa.Column('category_5', sa.String(length=100), nullable=True),
    sa.Column('category_6', sa.String(length=100), nullable=True),
    sa.Column('category_7', sa.String(length=100), nullable=True),
    sa.Column('category_8', sa.String(length=100), nullable=True),
    sa.Column('industry_code', sa.String(length=50), nullable=True),
    sa.Column('industry_name', sa.String(length=100), nullable=True),
    sa.Column('mpn', sa.String(length=100), nullable=True),
    sa.Column('gtin', sa.String(length=100), nullable=True),
    sa.Column('upc', sa.String(length=100), nullable=True),
    sa.Column('ean', sa.String(length=100), nullable=True),
    sa.Column('unspc', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prod_short_desc', sa.String(length=255), nullable=True),
    sa.Column('prod_long_desc', sa.Text(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('videos', sa.JSON(), nullable=True),
    sa.Column('documents', sa.JSON(), nullable=True),
    sa.Column('features_1', sa.String(length=255), nullable=True),
    sa.Column('features_2', sa.String(length=255), nullable=True),
    sa.Column('features_3', sa.String(length=255), nullable=True),
    sa.Column('features_4', sa.String(length=255), nullable=True),
    sa.Column('features_5', sa.String(length=255), nullable=True),
    sa.Column('features_6', sa.String(length=255), nullable=True),
    sa.Column('features_7', sa.String(length=255), nullable=True),
    sa.Column('features_8', sa.String(length=255), nullable=True),
    sa.Column('features_9', sa.String(length=255), nullable=True),
    sa.Column('features_10', sa.String(length=255), nullable=True),
    sa.Column('enrichment_status', sa.String(length=50), nullable=False),
    sa.Column('completeness_score', sa.Float(), nullable=True),
    sa.Column('completeness_details', sa.JSON(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_code')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_mpn'), 'products', ['mpn'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('user_code', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_code')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_code', sa.String(length=100), nullable=False),
    sa.Column('vendor_name', sa.String(length=30), nullable=False),
    sa.Column('contact_email', sa.String(length=30), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('business_type', sa.String(length=30), nullable=True),
    sa.Column('industry', sa.String(length=30), nullable=True),
    sa.Column('country', sa.String(length=30), nullable=True),
    sa.Column('vendor_logo_url', sa.JSON(), nullable=True),
    sa.Column('dept1_poc_name', sa.String(), nullable=True),
    sa.Column('dept1_email', sa.String(), nullable=True),
    sa.Column('dept1_phone', sa.String(), nullable=True),
    sa.Column('dept2_poc_name', sa.String(), nullable=True),
    sa.Column('dept2_email', sa.String(), nullable=True),
    sa.Column('dept2_phone', sa.String(), nullable=True),
    sa.Column('dept3_poc_name', sa.String(), nullable=True),
    sa.Column('dept3_email', sa.String(), nullable=True),
    sa.Column('dept3_phone', sa.String(), nullable=True),
    sa.Column('dept4_poc_name', sa.String(), nullable=True),
    sa.Column('dept4_email', sa.String(), nullable=True),
    sa.Column('dept4_phone', sa.String(), nullable=True),
    sa.Column('dept5_poc_name', sa.String(), nullable=True),
    sa.Column('dept5_email', sa.String(), nullable=True),
    sa.Column('dept5_phone', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_code')
    )
    op.create_index(op.f('ix_vendors_id'), 'vendors', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendors_id'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_mpn'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
