"""create_vendor_table

Revision ID: f2ea980eea02
Revises: de8ae21daf80
Create Date: 2026-02-07 15:36:12.234097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2ea980eea02'
down_revision: Union[str, Sequence[str], None] = 'de8ae21daf80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_code', sa.String(length=100), nullable=False),
    sa.Column('vendor_name', sa.String(length=30), nullable=False),
    sa.Column('contact_email', sa.String(length=30), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('business_type', sa.String(length=30), nullable=True),
    sa.Column('industry', sa.String(length=30), nullable=True),
    sa.Column('country', sa.String(length=30), nullable=True),
    sa.Column('vendor_logo_url', sa.JSON(), nullable=True),
    sa.Column('dept1_poc_name', sa.String(), nullable=True),
    sa.Column('dept1_email', sa.String(), nullable=True),
    sa.Column('dept1_phone', sa.String(), nullable=True),
    sa.Column('dept2_poc_name', sa.String(), nullable=True),
    sa.Column('dept2_email', sa.String(), nullable=True),
    sa.Column('dept2_phone', sa.String(), nullable=True),
    sa.Column('dept3_poc_name', sa.String(), nullable=True),
    sa.Column('dept3_email', sa.String(), nullable=True),
    sa.Column('dept3_phone', sa.String(), nullable=True),
    sa.Column('dept4_poc_name', sa.String(), nullable=True),
    sa.Column('dept4_email', sa.String(), nullable=True),
    sa.Column('dept4_phone', sa.String(), nullable=True),
    sa.Column('dept5_poc_name', sa.String(), nullable=True),
    sa.Column('dept5_email', sa.String(), nullable=True),
    sa.Column('dept5_phone', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_code')
    )
    op.create_index(op.f('ix_vendors_id'), 'vendors', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendors_id'), table_name='vendors')
    op.drop_table('vendors')
    # ### end Alembic commands ###
